version: '3.8'

services:
  database:
    image: postgres:15
    container_name: book-api-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./container-data/postgres:/var/lib/postgresql/data

networks:
  local:
    name: local
